### PR TITLE
Addeing v1 folder and new account key images

### PR DESCRIPTION
**Pull request by grahamcruse**
Images for v1 docs.

@ndobri

### CODE REVIEW

**Comment by ndobri** [comment]
Android chat send button is from the old designs. Also I'll have a quick design run through with @jonnybelton in few minutes so we'll know how the final screen shot will look like.

**Comment by grahamcruse** [comment]
This PR is not intended to be the final state, just an initial commit for further update.

**Comment by grahamcruse** [comment]
@ndobri removed the Android placeholders, you can add new images as desired.

**Comment by ndobri** [comment]
:+1: sorry for the delay, add the placeholders please

**Pull request merged**
