### PR TITLE
Adds email transcript images for docs

### PR DESCRIPTION
**Pull request by ndobri**
#### Changes
- Adds images for email transcript alert/dialog configuration
#### Reviewers
- @lawlesspaul @oarrabi @chucknado 
#### References

[Jira](https://zendesk.atlassian.net/browse/MSDK-1016)
#### Risks
- low

### CODE REVIEW

**Comment by chucknado** [comment]
@ndobri Is the purpose of these images to get them hosted so we can use them in the docs? We typically host images on AWS S3. Let me know if you want me to upload them.

The images are also too large for the docs. I resized and uploaded them to S3:

https://zen-marketing-documentation.s3.amazonaws.com/docs/en/email_transcript_ios.png
https://zen-marketing-documentation.s3.amazonaws.com/docs/en/email_transcript_android.png

Please use these links in the docs.

**Comment by ndobri** [comment]
@chucknado this was the process of uploading images so far afaik. Can you send me an email with what the process should be with aws now. PS. I think we still need to merge this and keep as backup assets?

**Comment by chucknado** [comment]
I don't think there's an official policy, but the preference for our public-facing docs is to use a hosting service built for high-traffic, mission-critical websites. Including @maximeprades for his thoughts.

For other projects, the team has cc'ed me on the PR and asked that I upload the images to S3. Sending images through the Docs team is also a useful QA step.

**Comment by chucknado** [comment]
BTW, you can merge if you want to keep backups of the images. :+1:

**Pull request merged**
